### ISSUE TITLE
Can't find or install new gems after communizing

### ISSUE THREAD

**Issue by olivierlacan** [tpope/rbenv-communal-gems#11]
After installing an communizing gems (which errored a few times per Ruby version due to gems installed with sudo) I'm seeing this issue on multiple Ruby versions I have installed:

```
/Users/olivierlacan/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'thor' (>= 0) among 0 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/olivierlacan/.gem/ruby/2.2.0:/Users/olivierlacan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0', execute `gem env` for more information
  from /Users/olivierlacan/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
  from /Users/olivierlacan/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
  from /Users/olivierlacan/.rbenv/versions/2.2.0/bin/thor:22:in `<main>'
```

$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: 
  - RUBY EXECUTABLE: /Users/olivierlacan/.rbenv/versions/2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /bin
  - SPEC CACHE DIRECTORY: /Users/olivierlacan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/olivierlacan/.rbenv/versions/2.2.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - 
     - /Users/olivierlacan/.gem/ruby/2.2.0
     - /Users/olivierlacan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--env-shebang"
     - "gemhome" => ""
     - :benchmark => false
     - :sources => ["https://rubygems.org/"]
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/olivierlacan/.rbenv/versions/2.2.0/bin
     - /Users/olivierlacan/.rbenv/libexec
     - /Users/olivierlacan/.rbenv/plugins/ruby-build/bin
     - /Users/olivierlacan/.rbenv/plugins/rbenv-sudo/bin
     - /Users/olivierlacan/.rbenv/plugins/rbenv-communal-gems/bin
     - /Users/olivierlacan/.rbenv/shims
     - /Users/olivierlacan/.rbenv/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/local/heroku/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin
```

As you can see the `INSTALLATION DIRECTORY` is blank. In `/Users/olivierlacan/.gem/ruby/2.2.0` I find only a `cache` directory with `bundler-1.8.2.gem` inside. You can also see that the first `GEM PATHS` is blank. This is most likely what causes:

```
$ gem install bundler
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_s_mkdir - 
```

Upon checking `~/.rbenv/gems/` I can only find a `2.0.0` directory there despite having the following Rubies installed:

```
$ rbenv versions
  system
  1.9.2-p330
  1.9.3-p392
  1.9.3-p448
  1.9.3-p484
  1.9.3-p545
  1.9.3-p550
  1.9.3-p551
  2.0.0-p247
  2.0.0-p353
  2.0.0-p481
  2.0.0-p594
  2.0.0-p598
  2.1.0
  2.1.1
  2.1.2
  2.1.4
  2.1.5
* 2.2.0 (set by /Users/olivierlacan/.rbenv/version)
  2.2.0-dev
  jruby-1.7.18
  jruby-1.7.6
```

So it looks like rbenv-communal-gems removed all my installation directories except for the one of the Ruby version I ran it from.

**Comment by olivierlacan** [comment]
Alright. The solution for everyone in a similar situation until someone else chimes in is to recreate the directory structure expected in `~/.rbenv/gems/<ruby_version>`, which is:

- bin
- cache
- extensions
- specifications
- build_info
- doc
- gems

And then go fix the `gemrc` file in `~/.rbenv/versions/<ruby_version>/etc`.

In my case it contained:
```
# added by rbenv communize
install: "--env-shebang"
gemhome: ""
```

Which I changed to:

```
# added by rbenv communize
install: "--env-shebang"
gemhome: "/Users/olivierlacan/.rbenv/gems/2.2.0"
```

Since this was for Ruby 2.2.0.

Not sure what went wrong during communize. :disappointed:

**Comment by olivierlacan** [comment]
FYI in `~/.rbenv/versions/1.9.2-p330/etc/gemrc` was:

```
gemhome: "/Users/olivierlacan/.rbenv/gems/"
```

So that's a different way communize didn't work as expected.

**Comment by rapidror** [comment]
Thanks for the post, when I switched ruby version I had the same error because my `INSTALLATION DIRECTORY` was blank. I had to `export GEM_HOME=$HOME/.gem`
